# application.properties (src/main/resources)
!aws.region=us-east-1
!database.url=${DATABASE_URL}
!database.writer=${DATABASE_WRITER}
!database.password=${DATABASE_PW}
!data.warehouse.bucket=${DATA_WAREHOUSE_BUCKET}
!aws.amtk.replication.bucket=${AWS_AMTK_REPLICATION_BUCKET_NAME}
!enable.data.warehouse=${ENABLE_DATA_WAREHOUSE:false}
!enable.replication=${ENABLE_REPLICATION:false}
powertools.log.level=${POWERTOOLS_LOG_LEVEL:ERROR}  
powertools.logger.sample=${POWERTOOLS_LOGGER_SAMPLE_RATE:0.03}
powertools.service.name=${POWERTOOLS_SERVICE_NAME:LogFileIndexer}
powertools.metrics.namespace=${POWERTOOLS_METRICS_NAMESPACE:LogFileIndexer}
powertools.tracer.capture.response=${POWERTOOLS_TRACER_CAPTURE_RESPONSE:true}
powertools.tracer.capture.error=${POWERTOOLS_TRACER_CAPTURE_ERROR:true}
scac=${SCAC:AMTK}