// application.properties (src/main/resources)
aws.region=us-east-1
database.url=${DATABASE_URL}
database.writer=${DATABASE_WRITER}
database.password=${DATABASE_PW}
data.warehouse.bucket=${DATA_WAREHOUSE_BUCKET}
aws.amtk.replication.bucket=${AWS_AMTK_REPLICATION_BUCKET_NAME}
enable.data.warehouse=${ENABLE_DATA_WAREHOUSE:false}
enable.replication=${ENABLE_REPLICATION:false}