// Copyright Wabtec Inc. 2025. All rights reserved
// @author Pete Kofod
package com.wabtec.railwaynet.strolrloglambda.repository;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;

import org.junit.jupiter.api.AfterAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import com.wabtec.railwaynet.strolrloglambda.entity.LogFile;

import uk.org.webcompere.systemstubs.environment.EnvironmentVariables;
import uk.org.webcompere.systemstubs.jupiter.SystemStub;
import uk.org.webcompere.systemstubs.jupiter.SystemStubsExtension;

@ExtendWith(SystemStubsExtension.class)
class JdbcLogFileRepositoryTest {

    @SystemStub
    private final EnvironmentVariables envVars = new EnvironmentVariables();

    private static Connection connection;

@BeforeAll
@SuppressWarnings("unused")
static void setupDatabase() throws SQLException {
    connection = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");
    connection.createStatement().execute("""
        CREATE TABLE logfileindex (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mark VARCHAR(10),
        locoNumber INT,
        device VARCHAR(20),
        endTime TIMESTAMP,
        logFilePath VARCHAR(100)
        )
    """);
}

    @AfterAll
    @SuppressWarnings("unused")
    static void cleanup() throws SQLException {
        connection.close();
    }

    @Test
    void save_insertsRecord() throws Exception {
        org.h2.jdbcx.JdbcDataSource h2 = new org.h2.jdbcx.JdbcDataSource();
        h2.setURL("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");

        var repo = new JdbcLogFileRepository(h2);
        var logFile = new LogFile("MK", 42, "DEV", LocalDateTime.parse("2025-01-01T12:34:56"), "/path/file");
        repo.save(logFile);

        var rs = connection.createStatement()
                        .executeQuery("SELECT mark, locoNumber, device, endTime, logFilePath FROM logfileindex");
        assertTrue(rs.next());
        assertEquals("MK", rs.getString("mark"));
        assertEquals(42, rs.getInt("locoNumber"));
        assertEquals("DEV", rs.getString("device"));
       assertEquals(Timestamp.valueOf("2025-01-01 12:34:56"), rs.getTimestamp("endTime"));

        assertEquals("/path/file", rs.getString("logFilePath"));
        assertFalse(rs.next());
    }

    @Test
    void constructor_missingEnv_throws() {
        envVars.set("DB_URL", null); // simulate missing
        envVars.set("DB_USER", "user"); // present
        envVars.set("DB_PASSWORD_SECRET_NAME", "mySecret"); // present

        IllegalStateException ex = assertThrows(IllegalStateException.class, JdbcLogFileRepository::new);
    assertTrue(ex.getMessage().contains("DB_URL"));
    }
}
