hibernate.dialect org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class org.postgresql.Driver
hibernate.connection.url jdbc:postgresql://m-ris-postgres-db.cjtxx3u946t0.us-east-1.rds.amazonaws.com:5432/strolr-logfiledb
hibernate.connection.username strolr_logfiledb_writer
hibernate.connection.password ygZ7XuENjsBHwVyy